/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundEffects: typeof import('./src/components/BackgroundEffects.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    Clock: typeof import('./src/components/Clock.vue')['default']
    EqualizerPanel: typeof import('./src/components/EqualizerPanel.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HorizontalSlider: typeof import('./src/components/HorizontalSlider.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    NotificationToast: typeof import('./src/components/NotificationToast.vue')['default']
    OverlayPanel: typeof import('./src/components/OverlayPanel.vue')['default']
    PagedList: typeof import('./src/components/PagedList.vue')['default']
    PagedSquareCardList: typeof import('./src/components/PagedSquareCardList.vue')['default']
    PlayerArtwork: typeof import('./src/components/PlayerArtwork.vue')['default']
    PlayerArtworkMini: typeof import('./src/components/PlayerArtworkMini.vue')['default']
    PlayerControls: typeof import('./src/components/PlayerControls.vue')['default']
    PlayerFullscreen: typeof import('./src/components/PlayerFullscreen.vue')['default']
    PlayerMini: typeof import('./src/components/PlayerMini.vue')['default']
    PlayerTrackInfo: typeof import('./src/components/PlayerTrackInfo.vue')['default']
    PodcastCardList: typeof import('./src/components/PodcastCardList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    SquareCard: typeof import('./src/components/SquareCard.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    TouchSlider: typeof import('./src/components/TouchSlider.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
  }
}
